#ifndef FIRMWARE_BLOB_BOOT_POLICY_H
#define FIRMWARE_BLOB_BOOT_POLICY_H

typedef enum
{
	BOARD_BOOT_POLICY_NOT_SET,
	BOARD_BOOT_POLICY_PRODUCTION,
	BOARD_BOOT_POLICY_SIGNED,
	BOARD_BOOT_POLICY_DEVELOPMENT_PROJECT_ID,
	BOARD_BOOT_POLICY_DEVELOPMENT,
	BOARD_BOOT_POLICY_COUNT
} board_boot_policy_t;

#endif // FIRMWARE_BLOB_BOOT_POLICY_H
