# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (c) 2023, Cegelec a.s.
#

obj-y += src/rsa-verify/rsa.o src/rsa-verify/rwsig.o src/rsa-verify/sha256.o
obj-y += src/verify_blob_integrity.o src/validate_blob.o
