// SPDX-License-Identifier: GPL-2.0+
#ifndef DEVICE_PARAMS_DP_ERR_FEEDBACK_H
#define DEVICE_PARAMS_DP_ERR_FEEDBACK_H

typedef enum
{
	DEVPARAMS_ERR_NONE,
	DEVPARAMS_ERR_ETH_SETTINGS_BAD_CRC,
	DEVPARAMS_ERR_ETH_SETTINGS_INVALID_MAC,
	DEVPARAMS_ERR_ETH_SETTINGS_INVALID_IPADDR,
	DEVPARAMS_ERR_ETH_SETTINGS_INVALID_NETMASK,
	DEVPARAMS_ERR_ETH_SETTINGS_INVALID_GATEWAY,
	DEVPARAMS_ERR_EMMC_LAYOUT_BAD_CRC,
	DEVPARAMS_ERR_EMMC_LAYOUT_INVALID_STATE_SIZE,
	DEVPARAMS_ERR_EMMC_LAYOUT_INVALID_BACKUP_SIZE,
	DEVPARAMS_ERR_EMMC_LAYOUT_INVALID_SW_SIZE,
	DEVPARAMS_ERR_EMMC_LAYOUT_OVERLAP,
	DEVPARAMS_ERR_EMMC_LAYOUT_ALIGNMENT,
	DEVPARAMS_ERR_INTERNAL,
	DEVPARAMS_ERR_COUNT
} device_params_err_t;

const char *get_dp_err_feedback(device_params_err_t err);

#endif // DEVICE_PARAMS_DP_ERR_FEEDBACK_H
