# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (c) 2023, Cegelec a.s.
#
# (C) Copyright 2000-2007
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.

#obj-y += device_params.o

obj-y += dp_boot_policy_helpers.o dp_err_feedback.o emmc_layout.o emmc_state.o ethernet_settings.o fb_env_vars.o flash_params.o
